In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 시각화 설정
%matplotlib
%config InlineBackend.figure_format = 'svg'

plt.rcParams['figure.figsize'] = [10, 5]
plt.ion() # enable the interactive mode

Using matplotlib backend: Qt5Agg

In [3]:
df = pd.read_csv('./data/exp_result.csv')

In [4]:
df

    Unnamed: 0  fs_size   exec_time          mae
0            0       42  302.114446   712.448258
1            1       41  339.183835   712.528562
2            2       40  331.770581   712.471850
3            3       39  315.939503   712.362637
4            4       38  304.002406   715.980223
5            5       37  295.678168   717.656929
6            6       36  290.710381   719.700113
7            7       35  281.493242   721.401326
8            8       34  278.033372   725.225015
9            9       33  273.282266   725.252212
10          10       32  266.276181   729.307858
11          11       31  254.831145   731.924819
12          12       30  244.556142   731.893861
13          13       29  231.719425   749.636083
14          14       28  228.275135   750.096478
15          15       27  219.712626   750.491307
16          16       26  214.236392   752.655362
17          17       25  212.582432   753.181766
18          18       24  205.914117   753.679138
19          19       23  197.330113   758.290819
20          20       22  187.805475   759.842345
21          21       21  179.510340   761.824058
22          22       20  170.888207   762.098020
23          23       19  169.442170   768.383541
24          24       18  158.611240   772.175202
25          25       17  149.577214   770.966234
26          26       16  142.923157   780.751576
27          27       15  129.545483   786.992716
28          28       14  128.235072   803.532402
29          29       13  124.751265   905.706852
30          30       12  115.087567   931.583807
31          31       11  105.311171   937.493363
32          32       10  107.396338   949.522758
33          33        9  102.560159   959.792113
34          34        8   96.971271   960.028988
35          35        7  102.420051  1016.898880
36          36        6   90.149166  1041.475018
37          37        5   63.106214  1933.308689
38          38        4   39.589017  2059.335472
39          39        3    2.779135  2040.204815
40          40        2    2.123982  2080.445211

In [6]:
# Multi y-axis 차트 시각화

fig, ax = plt.subplots()
fig.subplots_adjust(right=0.75)

twin1 = ax.twinx()

p1, = ax.plot(df.fs_size, df.mae,  "b-", label="MAE")
p2, = twin1.plot(df.fs_size, df.exec_time, "r-", label="Execution Time (sec.)")

ax.set_xlim(42, 2)
ax.set_ylim(0, df.mae.max())
twin1.set_ylim(0, df.exec_time.max())

ax.set_xlabel("Number of Features")
ax.set_ylabel("MAE")
twin1.set_ylabel("Execution Time (sec.)")

ax.yaxis.label.set_color(p1.get_color())
twin1.yaxis.label.set_color(p2.get_color())

tkw = dict(size=4, width=1.5)
ax.tick_params(axis='y', colors=p1.get_color(), **tkw)
twin1.tick_params(axis='y', colors=p2.get_color(), **tkw)

ax.tick_params(axis='x', **tkw)

ax.legend(handles=[p1, p2], loc='upper center')

plt.show()